config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'   
  }
  devise_scope :user do
    get 'signup', to: 'users/registrations#signup'
    get 'delivery_info', to: 'users/registrations#new_delivery_info'
    post 'delivery_info', to: 'users/registrations#create_delivery_info'
  end


  # 仮置き
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'edit_category_children', defaults: { format: 'json' }
      get 'edit_category_grandchildren', defaults: { format: 'json' }
    end
    resources :card do
      member do
        post 'buy' ,to: 'card#buy'
        post 'pay', to: 'card#pay'
        get 'confirm'
      end
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :users, only: [:show] do
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, :first_name, :last_name, :first_name_hurigana, :last_name_hurigana, :birthday ,presence: true
  has_one :delivery_info
  has_one :card, dependent: :destroy
  has_many :items, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up

  def signup
    @user = User.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @delivery_info = @user.build_delivery_info
    render :new_delivery_info
  end

  def create_delivery_info
    @user = User.new(session["devise.regist_data"]["user"])
    @delivery_info = DeliveryInfo.new(delivery_info_params)
    unless @delivery_info.valid?
      flash.now[:alert] = @delivery_info.errors.full_messages
      render :new_delivery_info and return
    end
    @user.build_delivery_info(@delivery_info.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
    redirect_to root_path
  end

  protected

  def delivery_info_params
    params.require(:delivery_info).permit(:first_name, :last_name, :first_name_hurigana, :last_name_hurigana, :postal_code, :city, :street, :building_name, :room_number, :phone_number, :prefecture_id)
  end
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if user_signed_in? 
      @user = User.find(params[:id])
      if not current_user.id == @user.id
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
end

app/views/users/show.html.haml
= render partial: 'items/header'


.user-my-page-main
  .my-container
    .my-side
      .my-side__navigation
        .my-side__navigation__list
          %li
            = link_to '#', class: 'my-side__navigation__list__item active' do
              マイページ
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              お知らせ
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              いいね！一覧
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              出品する
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              下書き一覧
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              出品した商品-出品中
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              出品した商品–取引中
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              出品した商品–売却中
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              購入した商品–取引中
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              購入した商品–過去の取引
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              ニュース一覧
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              評価一覧
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              ガイド
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              お問い合わせ
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
        .my-side__navigation__head メルペイ
        .my-side__navigation__list
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              売上・振込申請
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              ポイント
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
        .my-side__navigation__head 設定
        .my-side__navigation__list
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              プロフィール
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              発送元・お届け先住所
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            - if current_user.card
              = link_to card_index_path, class: 'my-side__navigation__list__item', data: { turbolinks: false} do
                クレジットカード登録・削除
                .my-side__navigation__list__item__icon
                  = icon('fas', 'angle-right')
            - else
              = link_to new_card_path, class: 'my-side__navigation__list__item', data: { turbolinks: false} do
                クレジットカード登録・削除
                .my-side__navigation__list__item__icon
                  = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              メール/パスワード
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              本人情報
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              電話番号の確認
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')
          %li
            = link_to '#', class: 'my-side__navigation__list__item' do
              ログアウト
              .my-side__navigation__list__item__icon
                = icon('fas', 'angle-right')

    .my-content
      .mypage-content
        = link_to '#', class: 'content-link' do
          %figure
            = image_tag asset_path('member_photo_noimage_thumb.png'), class: "icon"
          %h2.test-name
            = @user.nickname
          .mypage-content-number
            .evaluation
              評価
              %span.count 0
            .exhibition
              出品数
              %span.count
                = @user.items.count
      .tabs
        %ul.content-tabs
          %li.information
            %h3
              = link_to '#', class: 'content-btn' do
                お知らせ
          %li.todo
            %h3
              = link_to '#', class: 'content-btn' do
                やることリスト
        .tab-boxs
          %ul{id: 'tab-box-notification', class: 'tab-box'}
            %li.tab-box__item
              = link_to '#', class: 'tab-box__item__link' do
                .tab-box__item__icon
                  = image_tag asset_path('icon_brand.png'), class: "icon"
                .tab-box__item__link__body
                  .tab-box__item__link__body__text
                    《この通知を受け取ったあなた限定》「500ポイントバック」のクーポンをプレゼントしました！
                  .tab-box__item__link__body__time
                    = icon('far', 'clock')
                    %span 1日前
              = icon('fas', 'angle-right', class: 'arrow')
            %li.tab-box__item
              = link_to '#', class: 'tab-box__item__link' do
                = image_tag asset_path('icon_brand.png'), class: "icon"
                .tab-box__item__link__body
                  .tab-box__item__link__body__text
                    事務局から個別メッセージ「ログイン通知」
                  .tab-box__item__link__body__time
                    = icon('far', 'clock')
                    %span 1日前
              = icon('fas', 'angle-right', class: 'arrow')

            %li.tab-box__list
              = link_to '一覧を見る', '#'
      .second-tabs
        %h2.second-tabs-head 購入した商品
        %ul.content-tabs
          %li.transactions
            %h3
              = link_to '#', class: 'content-btn' do
                取引中
          %li.post-transactions
            %h3
              = link_to '#', class: 'content-btn' do
                過去の取引
        .tab-boxs
          %ul{id: 'tab-box-during-trading', class: 'tab-box'} 
            %li.during-trading
              取引中の商品がありません

= render partial: 'items/app-banner'

= render partial: 'items/footer'

= render partial: 'items/purchase-btn'