config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'   
  }
  devise_scope :user do
    get 'signup', to: 'users/registrations#signup'
    get 'delivery_info', to: 'users/registrations#new_delivery_info'
    post 'delivery_info', to: 'users/registrations#create_delivery_info'
  end


  # 仮置き
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'edit_category_children', defaults: { format: 'json' }
      get 'edit_category_grandchildren', defaults: { format: 'json' }
    end
    resources :card do
      member do
        post 'buy' ,to: 'card#buy'
        post 'pay', to: 'card#pay'
        get 'confirm'
      end
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :users, only: [:show] do
  end
end

app/models/item.rb
class Item < ApplicationRecord
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :category
  validates :name, :category_id, :content, :status, :postage, :prefecture_id, :shipping_days, :price ,presence: true
  validates :images,presence: true
  belongs_to :user
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :destroy]
  def index
    @items = Item.where(buyer_id: nil).includes(:images).limit(9).order('created_at DESC')
  end

  def new
    if user_signed_in?
      @item = Item.new
      @item.images.build
      
      @category_parent_array = Category.where(ancestry: nil).pluck(:name)
      @category_parent_array.unshift("選択してください")
    else
      redirect_to root_path
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else   
      @item.images.build
      @category_parent_array = Category.where(ancestry: nil).pluck(:name)
      @category_parent_array.unshift("選択してください")
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    if user_signed_in?
      @card = Card.find_by(user_id: current_user.id)
    end
  end
  def get_category_children  
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children  
  end

  def edit_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children  
  end
  
  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def edit_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def edit
    @category_parent = @item.category.root.name
    grandchild_category = @item.category
    child_category = grandchild_category.parent
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    @category_parent_array.unshift("選択してください")
    @category_children_array = Category.where(ancestry: child_category.ancestry)
    @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry)
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      @category_parent = @item.category.root.name
      grandchild_category = @item.category
      child_category = grandchild_category.parent
      @category_parent_array = Category.where(ancestry: nil).pluck(:name)
      @category_parent_array.unshift("選択してください")
      @category_children_array = Category.where(ancestry: child_category.ancestry)
      @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry)
      render :edit
    end
  end
  
  def destroy
    if @item.destroy
      flash[:item_delete_notice] = "削除が完了しました"
      redirect_to root_path
    else
      flash[:item_delete_alert] = '削除が失敗しました'
      render :show
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :category_id, :content, :brand, :status, :postage, :prefecture_id, :shipping_days, :price, images_attributes: [:url, :_destroy, :id]).merge(user_id: current_user.id)
  end
  
  def set_item
    @item = Item.find(params[:id])
    if user_signed_in? && @item.user_id == current_user.id
    else
      redirect_to root_path
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_app-banner.html.haml
/appバナー
%aside.app-banner
  .app-banner__inner
    .app-banner__inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    .app-banner__inner__text
      今すぐ無料ダウンロード！
    .app-banner__inner__icon
      = link_to "#", class: "app-banner__inner__icon__apple-store-link" do
        = image_tag asset_path('apple-store.svg'), class: "app-banner__inner__icon__apple-store-link__img"
      = link_to "#", class: "app-banner__inner__icon__google-play-link" do
        = image_tag asset_path('google-play.svg'), class: "app-banner__inner__icon__google-play-link__img"

app/views/items/_footer.html.haml
/footer部分
.footer
  %ul.footer__contents
    %li.footer__contents__content
      %h2.footer__contents__content__head
        FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社）", "#"
        %li
          = link_to "プライバシーポリシー", "#"
        %li
          = link_to "FURIMA利用規約", "#"
        %li
          = link_to "ポイントに関する特約", "#"
    %li.footer__contents__content
      %h2.footer__contents__content__head
        FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧", "#"
        %li
          = link_to "ブランド一覧", "#"
    %li.footer__contents__content
      %h2.footer__contents__content__head
        ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド", "#"
        %li
          = link_to "FURIMAロゴ利用ガイドライン", "#"
        %li
          = link_to "お知らせ", "#"
  .footer__logo
    = link_to root_path do
      = image_tag asset_path('logo-white.png')
  %p
    © FURIMA

app/views/items/_form.html.haml
%main.items-new-main
  .main__center
    = form_for @item, html: { id: :item_form }  do |form|
      .content
        .content__title
          %h2.content__title__name
            出品画像
          %h2.content__title__tag
            必須
        .content__text
          最大10枚までアップロードできます

        .uplord-image-files-field
          .image-previews
            - if @item.persisted?
              - @item.images.each_with_index do |image, i|
                .image-preview{"data-index": "#{i}"}
                  .image-preview__image-box
                    = image_tag image.url.url, data: { index: i }, width: "118", height: '118', class: 'image'
                  .image-preview__btn
                    %label{ for: "item_images_attributes_#{i}_url", class: "image-edit" }
                      編集
                    %span.image-remove 削除

            -# 実際に押すことができるボタン
            - if @item.persisted?
              %label{ class: "add-btn", for: "add-select-image", "data-count": "#{@item.images.count}"}
                .label-box
                  = image_tag asset_path('icon_camera.png'), class: 'icon-camera'
                  %p.upload-info
                    クリックして画像をアップロード              
            - else
              %label{ class: "add-btn", for: "item_images_attributes_0_url", "data-index": "0"}
                .label-box
                  = image_tag asset_path('icon_camera.png'), class: 'icon-camera'
                  %p.upload-info
                    クリックして画像をアップロード
          = form.fields_for :images do |image|
            .select-image{ "data-index": "#{image.index}" }
              = image.file_field :url, class: "input-image", id:"item_images_attributes_#{image.index}_url"
            - if @item.persisted?
              = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'

            -# edit機能の時は追加で写真を投稿できるようにするため
          - if @item.persisted?
            .select-image{ "data-index": "#{@item.images.count}" }
              = file_field_tag :url, class: "input-image", name: "item[images_attributes][#{@item.images.count}][url]", id: 'add-select-image'         
        .image-error-box
        - if @item.errors.messages[:images] != []
          %p.item-form-alert.image-alert
            画像を選択してください

      .content
        .content__title
          %h2.content__title__name
            商品名
          %h2.content__title__tag
            必須
        = form.text_field :name, class: "input-text", placeholder: "40字まで"
        - if @item.errors.messages[:name] != []
          %p.item-form-alert 
            商品名を入力してください
        .content__title
          %h2.content__title__name
            商品の説明
          %h2.content__title__tag
            必須
        = form.text_area :content, rows: "6", class: "input-longtext", placeholder: "商品の説明（必須 1,000文字以内)\n（色、素材、重さ、定価、注意点など）\n\n 例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"       
        - if @item.errors.messages[:content] != []
          %p.item-form-alert 
            商品の説明を入力してください

        -# jsで入力文字数を表示
        %h4.count-word
          %span.count-word__num 0
          \/1000

      .content
        %h1.content__info
          商品の詳細

        -# カテゴリー機能      
        .create-category
          .create-category__form
            %a.create-category__form__name
              カテゴリー
            %a.create-category__form__tag
              必須
            - if @item.errors.messages[:category] != []
              %p.item-form-alert.category-alert 
                カテゴリーを選択してください    
            .create-category__form__select
              .create-category__form__select__box
                = form.select :category_id, @category_parent_array, {selected: @category_parent}, {class: 'create-category__form__select__box__btn', id: 'parent_category'}
              - if @item.persisted?
                .create-category__form__select__added#children_wrapper
                  .create-category__form__select__box
                    = form.select :category_id, options_for_select(@category_children_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "選択してください", selected: @item.category.parent.id}),{}, {class: 'create-category__form__select__box__btn', id: 'child_category'}
                .create-category__form__select__added#grandchildren_wrapper
                  .create-category__form__select__box
                    = form.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "選択してください", selected: @item.category.id}),{}, {class: 'create-category__form__select__box__btn', id: 'grandchild_category'}

        .content__title
          %h2.content__title__name
            ブランド
          %h2.content__title__tag-optional
            任意
        = form.text_field :brand, class: "input-text", placeholder: "例）シャネル"
        .content__title
          %h2.content__title__name
            商品の状態
          %h2.content__title__tag
            必須

        = form.select :status, [ ["選択してください",""], ["新品、未使用","新品、未使用"], ["未使用に近い", "未使用に近い"], ["目立った傷や汚れなし", "目立った傷や汚れなし"] ,["やや傷や汚れあり", "やや傷や汚れあり"], ["傷や汚れあり", "傷や汚れあり"], ["全体的に状態状態が悪い", "全体的に状態状態が悪い"] ], {}, class: "input-select"       
        - if @item.errors.messages[:status] != []
          %p.item-form-alert 
            商品の状態を選択してください

      .content
        %h1.content__info
          配送について
        .content__title
          %h2.content__title__name
            配送料の負担
          %h2.content__title__tag
            必須
        = form.select :postage, [ ["選択してください",""], ["送料込み(出品者負担)","送料込み(出品者負担)"], ["着払い(購入者負担)", "着払い(購入者負担)"]], {}, class: "input-select"
        - if @item.errors.messages[:postage] != []
          %p.item-form-alert 
            配送料の負担を選択してください
  
        .content__title
          %h2.content__title__name
            発送元の地域
          %h2.content__title__tag
            必須
        = form.collection_select :prefecture_id, Prefecture.all, :id, :name, {}, class: "input-select"
        - if @item.errors.messages[:prefecture_id] != []
          %p.item-form-alert 
            発送元の地域を選択してください

        .content__title
          %h2.content__title__name
            発送までの日数
          %h2.content__title__tag
            必須
        = form.select :shipping_days, [ ["選択してください",""], ["1〜2日で発送","1〜2日で発送"], ["2〜3日で発送", "2〜3日で発送"], ["4〜7日で発送", "4〜7日で発送"]], {}, class: "input-select"    
        - if @item.errors.messages[:shipping_days] != []
          %p.item-form-alert 
            発送までの日数を選択してください

      .content
        %h1.content__info
          価格 (¥300〜9,999,999)

        -# ここだけ横並びにしたいが、クラス名は変更したくないため
        .flex
          .content__title
            %h2.content__title__name
              販売価格
            %h2.content__title__tag
              必須
          .price
            %p.price__yen
              ¥
            = form.number_field :price, class: "input-price", placeholder: "0", min: 300, max: 9999999
        - if @item.errors.messages[:price] != []
          %p.item-form-alert.price-alert 
            販売価格を入力してください
        .calc-box
          %h3.calc-box__title
            販売手数料 (10%)         
          -# jsで計算結果を表示
          %p.calc-box__result.fee
            
        %hr.partition
        .calc-box
          %h3.calc-box__title
            販売利益          
          -# jsで計算結果を表示
          %p.calc-box__result.plofit
            
        .btn-area
          - if @item.persisted?
            = form.submit "編集を保存する", class: "submit-btn"
          - else
            = form.submit "出品する", class: "submit-btn"

          = form.submit "下書きに保存", class: "save-btn"
          = link_to "もどる", root_path, class:"back-btn"
        %h4.caution
          禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

app/views/items/_header.html.haml
/header部分
%header.header
  .header__content
    .header__content__main
      %h1.header__content__main__logo
        = link_to root_path, class: "header__content__main__logo__link" do
          = image_tag asset_path('logo.png'), class: "header__content__main__logo__link__img"
      .header__content__main__search-box
        %form.header__content__main__search-box__form
          %input.header__content__main__search-box__form__input{placeholder: "キーワードから探す"}
          %button.header__content__main__search-box__form__btn{type: "submit"}
            .header__content__main__search-box__form__btn__icon
              = image_tag asset_path('icon-search 1.png'), class: "header__content__main__search-box__form__btn__icon__img"
    .header__content__nav
      %ul.header__content__nav__left-list
        %li.header__content__nav__left-list__item
          = link_to "カテゴリー", "#", class: "header__content__nav__left-list__item__link"
        %li.header__content__nav__left-list__item
          = link_to "ブランド", "#", class: "header__content__nav__left-list__item__link" 
      %ul.header__content__nav__right-list
        - if user_signed_in?
          %li.header__content__nav__right-list__item
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__content__nav__right-list__item__link" 
          %li.header__content__nav__right-list__item
            = link_to "マイページ", user_path(current_user.id), class: "header__content__nav__right-list__item__link" 
        - else
          %li.header__content__nav__right-list__item
            = link_to "ログイン", new_user_session_path, class: "header__content__nav__right-list__item__link" 
          %li.header__content__nav__right-list__item
            = link_to "新規会員登録", signup_path, class: "header__content__nav__right-list__item__link"

app/views/items/_purchase-btn.html.haml
/購入ボタン
- if user_signed_in?
  = link_to new_item_path do
    .purchase-btn
      %span{class: "purchase-btn__text"}
        出品する
      = image_tag asset_path('icon_camera.png'), class: "purchase-btn__icon"
- else
  = link_to new_user_session_path do
    .purchase-btn
      %span{class: "purchase-btn__text"}
        出品する
      = image_tag asset_path('icon_camera.png'), class: "purchase-btn__icon"

app/views/items/_sub-footer.html.haml
-# トップページのフッター　
%footer.sub
  .sub-footer
    .sub-footer__content
      %ul
        %li<
          = link_to "#", id: "privacy" do
            プライバシーポリシー
        %li<
          = link_to "#", id: "tos" do
            FURIMA利用規約
        %li<
          = link_to "#", id: "tokutei" do
            特定商取引に関する規約
      .sub-footer__content__logo
        = image_tag asset_path('logo.png'), class: "sub-footer__content__logo__image"
      %p
        %small
          FURIMA,Inc.

          

app/views/items/_sub-header.html.haml
-# FURIMAのロゴ
.sub-header
  .sub-header__content
    %h1.sub-header__content__logo
      = link_to root_path do
        = image_tag asset_path('logo.png'), class: "sub-header__content__logo__image"

app/views/items/edit.html.haml
= render partial: 'sub-header'

= render partial: 'form'

= render partial: 'sub-footer'

app/views/items/index.html.haml
= render partial: 'header'

/コンテンツ部分
.main
  -if flash[:card_delete_notice]
    .flash-message
      = flash[:card_delete_notice]
  - if flash[:item_delete_notice]
    .flash-message
      = flash[:item_delete_notice]
  %section.main__visual
    .main__visual__content
      %h2.main__visual__content__subtitle
        %br
        人生を変えるフリマアプリ
      %p.main__visual__content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .main__visual__content__btn
        = link_to "#", class: "main__visual__content__btn__apple-store-link" do
          = image_tag asset_path('apple-store.svg'), class: 'main__visual__content__btn__apple-store-link__img'
        = link_to "#", class: "main__visual__content__btn__google-play-link" do
          = image_tag asset_path('google-play.svg'), class: 'main__visual__content__btn__google-play-link__img'
  
  %section.main__introduction
    %h2.main__introduction__subtitle
      FURIMAが選ばれる3つの理由
    %ul.main__introduction__lists
      %li.main__introduction__lists__list
        .main__introduction__lists__list__pict
          %span.main__introduction__lists__list__pict__number
            1
          = image_tag asset_path('pict-reason-01.jpg'), class: 'main__introduction__lists__list__pict__img'
        %h3.main__introduction__lists__list__text
          %span
            3分
          ですぐに出品
        %p.main__introduction__lists__list__description
          スマホで入力するだけで簡単に出品できる！
      %li.main__introduction__lists__list
        .main__introduction__lists__list__pict
          %span.main__introduction__lists__list__pict__number
            2
          = image_tag asset_path('pict-reason-02.jpg'), class: 'main__introduction__lists__list__pict__img'
        %h3.main__introduction__lists__list__text
          %span
            シンプル
          で使いやすい
        %p.main__introduction__lists__list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.main__introduction__lists__list.main__introduction__lists__list-last
        .main__introduction__lists__list__pict
          %span.main__introduction__lists__list__pict__number
            3
          = image_tag asset_path('pict-reason-03.jpg'), class: 'main__introduction__lists__list__pict__img'
        %h3.main__introduction__lists__list__text
          手数料
          %span
            業界最安
        %p.main__introduction__lists__list__description
          最大3%でお得に出品&購入！
  
  %section.main__middle-dl
    .main__middle-dl__inner
      %h2.main__middle-dl__inner__subtitle
        会員数日本一位
      %p.main__middle-dl__inner__text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .main__middle-dl__inner__btn
        = link_to "#", class: "main__middle-dl__inner__btn__apple-store-link" do
          = image_tag asset_path('apple-store.svg'), class: 'main__middle-dl__inner__btn__apple-store-link__img'
        = link_to "#", class: "main__middle-dl__inner__btn__google-play-link" do
          = image_tag asset_path('google-play.svg'), class: 'main__middle-dl__inner__btn__google-play-link__img'

  %section.main__key-features
    %h2.main__key-features__subtitle
      FURIMAの特徴
    .main__key-features__items
      %section.main__key-features__items__item
        = image_tag asset_path('icon-01.png'), class: 'main__key-features__items__item__img'
        %h3.main__key-features__items__item__subtitle
          簡単に売り買いできる
        %p.main__key-features__items__item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.main__key-features__items__item
        = image_tag asset_path('icon-03.png'), class: 'main__key-features__items__item__img'
        %h3.main__key-features__items__item__subtitle
          売上金は即日振込みに対応
        %p.main__key-features__items__item__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %section.main__key-features__items__item
        = image_tag asset_path('icon-04.png'), class: 'main__key-features__items__item__img'
        %h3.main__key-features__items__item__subtitle
          様々な支払いに対応
        %p.main__key-features__items__item__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  %section.main__pickup
    %h2.main__pickup__subtitle
      ピックアップアイテム
    .main__pickup__product
      .main__pickup__product__head
        = link_to "#", class: "main__pickup__product__head__link" do
          %h3.main__pickup__product__head__link__title
            商品一覧
          .items-box
            = render @items

= render partial: 'app-banner'

= render partial: 'footer'

= render partial: 'purchase-btn'

app/views/items/new.html.haml
= render partial: 'sub-header'

%main.items-new-main
  .main__center
    = form_for [@item] do |form|      
      .content
        .content__title
          %h2.content__title__name
            出品画像
          %h2.content__title__tag
            必須
        .content__text
          最大10枚までアップロードできます

        -# 最後にscssを当てる際に使用
        -# = form.fields_for :images do |i|
        -#   = i.label :url, class: "input-file" do
        -#     = image_tag asset_path('icon_camera.png'), class: 'icon-camera'
        -#     %p.input-file__info
        -#       ドラッグアンドドロップ <br> またはクリックしてファイルをアップロード
        -#     = i.file_field :url, class: "input-file__hidden"

        -# クラス名は全て仮置き
        #image-box
          = form.fields_for :images do |image|
            .js-file_group{"data-index" => "#{image.index}"}
              = image.file_field :url, class: "js-file"
              %br
              %span.js-remove 削除

      .content
        .content__title
          %h2.content__title__name
            商品名
          %h2.content__title__tag
            必須
        = form.text_field :name, class: "input-text", placeholder: "40字まで"
        .content__title
          %h2.content__title__name
            商品の説明
          %h2.content__title__tag
            必須
        = form.text_area :content, rows: "6", class: "input-longtext", placeholder: "商品の説明（必須 1,000文字以内)\n（色、素材、重さ、定価、注意点など）\n\n 例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"

        -# jsで入力文字数を表示
        %h4.count-word
          0/1000

      .content
        %h1.content__info
          商品の詳細
        
        -# カテゴリー機能
        .create-category
          .create-category__form
            %a.create-category__form__name
              カテゴリー
            %a.create-category__form__tag
              必須
            .create-category__form__select
              .create-category__form__select__box
                = form.select :category_id, @category_parent_array, {}, {class: 'create-category__form__select__box__btn', id: 'parent_category'}
        .content__title
          %h2.content__title__name
            ブランド
          %h2.content__title__tag-optional
            任意
        = form.text_field :brand, class: "input-text", placeholder: "例）シャネル"
        .content__title
          %h2.content__title__name
            商品の状態
          %h2.content__title__tag
            必須
        = form.select :status, [ ["新品、未使用",1], ["未使用に近い", 2], ["目立った傷や汚れなし", 3 ] ,["やや傷や汚れあり", 4], ["傷や汚れあり", 5], ["全体的に状態状態が悪い", 6] ], { include_blank: "選択してください", selected:"" }, class: "input-select"       

      .content
        %h1.content__info
          配送について
        .content__title
          %h2.content__title__name
            配送料の負担
          %h2.content__title__tag
            必須
        = form.select :postage, [ ["送料込み(出品者負担)",1], ["着払い(購入者負担)", 2]], { include_blank: "選択してください", selected:"" }, class: "input-select"       
  
        .content__title
          %h2.content__title__name
            発送元の地域
          %h2.content__title__tag
            必須
        = form.collection_select :prefecture_id, Prefecture.all, :id, :name, { include_blank: "選択してください", selected:"" }, class: "input-select"
  
        .content__title
          %h2.content__title__name
            発送までの日数
          %h2.content__title__tag
            必須
        = form.select :shipping_days, [ ["1〜2日で発送",1], ["2〜3日で発送", 2], ["4〜7日で発送", 3]], { include_blank: "選択してください", selected:"" }, class: "input-select"    

      .content
        %h1.content__info
          価格 (¥300〜9,999,999)

        -# ここだけ横並びにしたいが、クラス名は変更したくないため
        .flex
          .content__title
            %h2.content__title__name
              販売価格
            %h2.content__title__tag
              必須
          .price
            %p.price__yen
              ¥
            = form.number_field :price, class: "input-price", placeholder: "0", min: 300, max: 9999999
        .calc-box
          %h3.calc-box__title
            販売手数料 (10%)
          
          -# jsで計算結果を表示
          %p.calc-box__result
            -
        %hr.partition
        .calc-box
          %h3.calc-box__title
            販売利益
          
          -# jsで計算結果を表示
          %p.calc-box__result
            -
        .btn-area
          = form.submit "出品する", class: "submit-btn"
          = form.submit "下書きに保存", class: "save-btn"
          = link_to "もどる", "#", class:"back-btn"
        %h4.caution
          禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

= render partial: 'sub-footer'