config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'   
  }
  devise_scope :user do
    get 'signup', to: 'users/registrations#signup'
    get 'delivery_info', to: 'users/registrations#new_delivery_info'
    post 'delivery_info', to: 'users/registrations#create_delivery_info'
  end


  # 仮置き
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'edit_category_children', defaults: { format: 'json' }
      get 'edit_category_grandchildren', defaults: { format: 'json' }
    end
    resources :card do
      member do
        post 'buy' ,to: 'card#buy'
        post 'pay', to: 'card#pay'
        get 'confirm'
      end
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :users, only: [:show] do
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :month
  validates :card_id, :customer_id, presence: true
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :set_card, only: [:delete, :show, :buy, :confirm]
  before_action :set_item, only: [:confirm, :buy]
  before_action :new_card_action, only: [:new]
  require "payjp"
  Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)

  def pay #payjpとCardのデータベース作成を実施
    if user_signed_in?
      if params['payjp-token'].blank?
        redirect_to action: "new"
      else
        customer = Payjp::Customer.create(
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
        )
        @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
        if @card.save
          redirect_to root_path
        else
          redirect_to action: "new"
        end
      end
    else
      redirect_to root_path
    end
  end

  def delete #PayjpとCardデータベースを削除
    if user_signed_in?
      if @card.blank?
        redirect_to action: "new"
      else
        customer = Payjp::Customer.retrieve(@card.customer_id)
        if customer.delete && @card.delete
          flash[:card_delete_notice] = '削除しました。'
          redirect_to root_path
        else
          flash[:card_delete_alert] = '削除に失敗しました。'
          redirect_to action: "delete"
        end
      end
    else
      redirect_to root_path
    end
  end

  def show #Cardのデータpayjpに送り情報を取り出す
    if user_signed_in?
      if @card.blank?
        redirect_to action: "new" 
      else
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @default_card_information = customer.cards.retrieve(@card.card_id)
      end
    else
      redirect_to root_path
    end
  end

  def buy #クレジット購入
    if @item.buyer_id.blank?
      if @card.blank?
        redirect_to action: "new"
        flash[:alert] = '購入にはクレジットカード登録が必要です'
      else
        # @item = Item.find(params[:item_id])
        Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
        Payjp::Charge.create(
        amount: @item.price,
        customer: @card.customer_id,
        currency: 'jpy',
        )
        if @item.update(buyer_id: current_user.id)
          flash[:buy_notice] = '購入しました。'
          redirect_to item_path(@item.id)
        else
          flash[:buy_alert] = '購入に失敗しました。'
          redirect_to item_path(@item.id)
        end
      end
    else
      redirect_to root_path
    end

  end
  
  def confirm
  end

  private
  def set_card
    if user_signed_in?
      @card = Card.find_by(user_id: current_user.id)
      if @card.user_id =! current_user.id
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def new_card_action
    if user_signed_in?
      if not Card.find_by(user_id: current_user.id).nil?
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def set_item
    if user_signed_in?
      @item = Item.find(params[:item_id])
      if current_user.id == @item.user_id
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/confirm.html.haml
= render partial: 'items/sub-header'

%main.main-confirm
  .main__center-items
    %h1.content-head
      購入内容の確認

    .content-middle
      .item

        -# 商品の画像を表示今は仮置き
        .item__image-box
          = image_tag @item.images[0].url.url, class: 'item-image'
        
        -# 商品の名前、値段を表示
        .item__info
          %p.item__info__name
            商品名：
            = @item.name
          %p.item__info__price
            値段：
            = @item.price

    .content-bottom
      .content-bottom__inner
        .buy-price
          %h2.buy-price__name
            支払い金額：
          
          -# 支払い金額を表示
          %p.buy-price__result
            = @item.price
        %hr.partition
        = link_to "カードで購入" , buy_item_card_path(@item, @card), method: :post, class: "confirm-page-btn", data: { turbolinks: false}
= render partial: 'items/sub-footer'

app/views/card/new.html.haml
= render partial: 'items/sub-header'

%main.credits-new-main
  .main__center

    %h1.content-head
      クレジットカード情報入力

    .content-main
      = form_with url: pay_card_index_path, method: :post, html: { id: 'charge-form', class: "content",  name: "inputForm"} do |f|
        .content__title
          %h2.content__title__name
            カード番号
          %h2.content__title__tag
            必須
        = f.text_field :number, class: "input-text", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        .content__title
          %h2.content__title__name
            有効期限
          %h2.content__title__tag
            必須
        .date
          .select-date
            = f.collection_select :exp_month , Month.all, :id, :name, {}, class: 'input-select-half'
            %span 月/
          .select-date
            = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{prompt:"--"} , class: 'input-select-half', id: "exp_year", type: "text"
            %span 年
        .content__title
          %h2.content__title__name
            セキュリティコード
          %h2.content__title__tag
            必須
        = f.text_field :cvc, class: "input-text", placeholder: "カード背面4桁もしくは3桁の数字", maxlength: "4", id: "cvc"
        #card_token
        = f.submit '登録する', class: "submit-btn", id: 'token_submit'
= render partial: 'items/sub-footer'

app/views/card/show.html.haml
= render partial: 'items/sub-header'


-if flash[:card_delete_alert]
  .flash-message
    = flash[:card_delete_alert]

%main.credits-new-main
  .main__center

    %h1.content-head
      登録クレジットカード情報

    .content-main
      .content
        .content__title
          %h2.content__title__name
            カード番号：
            = "**** **** **** " + @default_card_information.last4
      
        .content__title
          %h2.content__title__name
            有効期限：
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
      = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
        %input{ type: "hidden", class: "submit-btn", name: "card_id", value: "" }
        %button.card-delete-btn 削除する

= render partial: 'items/sub-footer'